### ISSUE TITLE
Unable to load models on RX 6800

### ISSUE THREAD

**Issue by nonetrix** [EmbeddedLLM/vllm#21]
On my RX 6800 I seem to get `RuntimeError: FlashAttention only supports AMD MI200 GPUs or newer.` for some reason, I Googled that GPU and it seems to be RDNA2 like mine but for enterprise. Is this not supported on consumer AMD cards or something? Will there be support for loading it without FlashAttention? I am using the Docker image on NixOS

**Comment by jfactory07** [comment]
did you try this environment ? export VLLM_USE_FLASH_ATTN_TRITON=0. reference: https://docs.vllm.ai/en/latest/getting_started/amd-installation.html

**Comment by nonetrix** [comment]
I don't have the time but I have learned a little more since making this issue and that's probably the fix, should be added to readme if so
